### PR TITLE
Fix compliance of CanvasID file

### LINKED ISSUE #665: Fix compliance of CanvasID
https://github.com/BHoM/Grasshopper_UI/blob/c6c98c892264378bdf4ccb8cfeaf4099a5b5e28d/Grasshopper_Engine/Query/CanvasID.cs#L1

Added in #664 - needs copyright headers and documentation which were deemed acceptable to ignore for the PR which added it but need doing ASAP.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #665

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by jamesramsden-bh — APPROVED** [review]
Ok, checked for wording and typos, all fine.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
