### PR TITLE
Update Rhino Common references in line with Rhino Toolkit

### LINKED ISSUE #672: Should we updated Rhino_Common reference to match Rhino_Toolkit updates?
In this PR we updated to Rhino Common v6 [here](https://github.com/BHoM/Rhinoceros_Toolkit/pull/230/files#diff-d11b819fef7f550bcf3479454ade6750be68bd148d71407eee749a4a5dbd87eaL65-R72). Should we match this in Grasshopper UI to avoid any potential conflicts?

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/Rhinoceros_Toolkit/pull/230

   
### Issues addressed by this PR
Fixes #672

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by IsakNaslundBh — APPROVED** [review]
Happy with the updates. First tests in Grasshopper for Rhino6 as well as Rhino 7 works as intended.

**Pull request merged**
