### PR TITLE
Turn on settings change ability within Grasshopper

### LINKED ISSUE #698: BHoM UI Settings in Grasshopper UI
#### Description:

In view of this PR https://github.com/BHoM/BHoM_UI/pull/482 around allowing the user to select which disciplines/namespaces they want to have search visibility over. I'd like to see some GH-specific QoL adjustments added to this branch https://github.com/BHoM/Grasshopper_UI/tree/BHoM_UI-%23215-Settings as it's already a great starting point. 

1. Updated settings icon (red themed gear)
2. Boolean UI toggle component instead of double spike, self-deleting node

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #698 

As discussed and requested by @michaelhoehn

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 22175410770

**Review by Tom-Kingstone — APPROVED** [review]
Tested, and when setting the input to true, opens the settings menu properly with all of its functionality intact, and closes properly when saving/closing.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Review by michaelhoehn — APPROVED** [review]
Looks great! Happy to see this merged. Tested and working as expected.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
