### PR TITLE
Search in dropdowns unlocked

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_UI/pull/450
   
### Issues addressed by this PR

Closes #

### Test files

See https://github.com/BHoM/BHoM_UI/pull/450

### CODE REVIEW

**Review by adecler — APPROVED** [review]
Approved as part of the review for https://github.com/BHoM/BHoM_UI/pull/450

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
