### PR TITLE
Changed namespace for BH.Engine.Rhinoceros

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Changed namespace for `BH.Engine.Rhinoceros` to `BH.Engine.Adapters.Rhinoceros`

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
Good alignment from the Rhino changes, thanks @Tom-Kingstone

**Pull request merged**
