### PR TITLE
Update CanvasID query to return the same runtimeID for clusters

### LINKED ISSUE #667: BHoM Analytics Pop Up Window shows when a GH cluster is opened
#### Description:

As in the title, the popup opens once a GH cluster is opened. I can imagine it can drive one mad when working on real stuff that consists of multiple clusters.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #667

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by CKBoulter — APPROVED** [review]
Have tested on Grasshopper on main and got the pop up in the cluster. On this branch, the pop up does not appear in the cluster. Good!

**Comment by CKBoulter** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
